{
 "title": "RETO0 PANDAS",
 "time": { "from": "2025-09-27T00:00:00.000Z", "to": "now" },
 "refresh": "1d",
 "panels": [
  {
   "title": "Media Kill por Role",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "// Define el origen de los datos y el rango de tiempo.\nfrom(bucket: \"Reto0Pandas\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"lol_matches\")\n    |> filter(fn: (r) => r[\"jugador\"] == \"Messi goat\")\n    |> filter(fn: (r) => r[\"_field\"] == \"kills\")\n    |> group(columns: [\"role\"])\n    |> aggregateWindow(every: 1d, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Victorias y derrotas",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 0 },
   "targets": [
    {
     "query": "// Define el origen de los datos: el bucket \"Reto0Pandas\" y el rango de tiempo.\nfrom(bucket: \"Reto0Pandas\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    \n    // Filtra los datos para obtener solo los de la medida \"lol_matches\".\n    |> filter(fn: (r) => r[\"_measurement\"] == \"lol_matches\")\n    |> filter(fn: (r) => r[\"jugador\"] == \"Messi goat\")\n\n    // Selecciona un único campo por partida para asegurar que cada partida se cuente una sola vez.\n    |> filter(fn: (r) => r[\"_field\"] == \"kills\")\n\n    // Agrupa todos los datos basándose únicamente en el campo \"resultado\" (\"Win\" o \"Lose\").\n    // Esto es crucial para ignorar los campeones y tener solo dos series de datos.\n    |> group(columns: [\"resultado\"])\n\n    // Agrupa los resultados en ventanas de 1 día y cuenta cuántas partidas hay en cada grupo (victorias y derrotas).\n    |> aggregateWindow(every: 1d, fn: count, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Numero de Partidas diarias",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"Reto0Pandas\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"lol_matches\")\n  |> filter(fn: (r) => r[\"jugador\"] == \"Messi goat\")\n  \n  // 1. Aislamos una fila por cada partida para no contar de más\n  |> filter(fn: (r) => r[\"_field\"] == \"kills\") \n  \n  // 2. ¡EL PASO CLAVE! Forzamos que todos los campeones se traten como un único grupo\n  |> group() \n  \n  // 3. Ahora sí, contamos las filas (partidas) por día\n  |> aggregateWindow(every: 1d, fn: count, createEmpty: false)"
    }
   ]
  },
  {
   "title": "ORO MEDIO CONSEGUIDO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "query": "from(bucket: \"Reto0Pandas\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"lol_matches\")\n  |> filter(fn: (r) => r[\"_field\"] == \"goldEarned\")\n  |> filter(fn: (r) => r[\"jugador\"] == \"Messi goat\")\n  |> group() // Combina los datos de todos los campeones en una sola línea\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false) // Agrupa los datos por día y calcula la media"
    }
   ]
  },
  {
   "title": "MEDIA VISION",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"Reto0Pandas\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"lol_matches\")\n  |> filter(fn: (r) => r[\"_field\"] == \"visionScore\")\n  |> filter(fn: (r) => r[\"jugador\"] == \"Messi goat\")\n  |> group() // Elimina la agrupación por campeón y junta todo en una sola tabla.\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false) // Ahora calcula la media de esa única tabla."
    }
   ]
  },
  {
   "title": "MUERTES",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 11, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Reto0Pandas\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"lol_matches\")\n  |> filter(fn: (r) => r[\"_field\"] == \"deaths\")\n  |> filter(fn: (r) => r[\"jugador\"] == \"Messi goat\")\n  |> group(columns: [\"campeon\"])  \n  |> sum()"
    }
   ]
  },
  {
   "title": "KILL POR PJ",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 17, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Reto0Pandas\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"lol_matches\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kills\")\n  |> filter(fn: (r) => r[\"jugador\"] == \"Messi goat\")\n  |> group(columns: [\"campeon\"])\n  |> sum()"
    }
   ]
  },
  {
   "title": "DURACION MEDIA",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Reto0Pandas\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"lol_matches\")\n  |> filter(fn: (r) => r[\"_field\"] == \"duracion_min\")\n  |> filter(fn: (r) => r[\"jugador\"] == \"Messi goat\")\n  |> group(columns: [\"campeon\"])  // Agrupa los resultados por cada campeón\n  |> mean()                     // Calcula la media para cada grupo (campeón)"
    }
   ]
  }
 ]
}