{
 "title": "Reto0 Node-Red",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "TOP2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Asesinatos por personaje",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"reto0Node\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Top2\")\n  |> filter(fn: (r) => r[\"_field\"] == \"asesinatos\")\n  |> group(columns: [\"campeon\"])"
    }
   ]
  },
  {
   "title": "ASISTENCIAS POR PERSONAJE",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"reto0Node\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Top2\")\n  |> filter(fn: (r) => r[\"_field\"] == \"asistencias\")"
    }
   ]
  },
  {
   "title": "Daño Total Top2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"reto0Node\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Top2\")\n  |> filter(fn: (r) => r[\"_field\"] == \"danoTotalACampeones\")\n"
    }
   ]
  },
  {
   "title": "Vision",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "targets": [
    {
     "query": "from(bucket: \"reto0Node\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Top2\")\n  |> filter(fn: (r) => r[\"_field\"] == \"puntuacionDeVision\")"
    }
   ]
  },
  {
   "title": "TOP1",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Asistencia por personaje",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"reto0Node\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Top1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"asistencias\")"
      }
     ]
    },
    {
     "title": "Asesinatos por PJ",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"reto0Node\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Top1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"asesinatos\")\n  |> group(columns: [\"campeon\"])"
      }
     ]
    },
    {
     "title": "Vision",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "lengthkm" } },
     "targets": [
      {
       "query": "from(bucket: \"reto0Node\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Top1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"puntuacionDeVision\")"
      }
     ]
    },
    {
     "title": "Daño Total TOP1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 41 },
     "targets": [
      {
       "query": "from(bucket: \"reto0Node\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Top1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"danoTotalACampeones\")\n"
      }
     ]
    }
   ]
  },
  { "title": "Comparativa TOP1 VS TOP2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Muertes diarias",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"reto0Node\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Top1\" or r[\"_measurement\"] == \"Top2\")\n  |> filter(fn: (r) => r[\"_field\"] == \"muertes\")\n  |> group(columns: [\"_measurement\"])\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Mas Vision",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"reto0Node\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Top1\" or r[\"_measurement\"] == \"Top2\")\n  |> filter(fn: (r) => r[\"_field\"] == \"puntuacionDeVision\")\n  |> group(columns: [\"_measurement\"])\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Oro media diario",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 26 },
   "targets": [
    {
     "query": "from(bucket: \"reto0Node\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Top1\" or r[\"_measurement\"] == \"Top2\")\n  |> filter(fn: (r) => r[\"_field\"] == \"oroGanado\")\n  |> group(columns: [\"_measurement\"])\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false)\n"
    }
   ]
  }
 ]
}